package albr.com.mapper;

import albr.com.tax.dto.ProductRequest;
import albr.com.tax.dto.ProductResponse;
import albr.com.tax.mapper.ProductMapper;
import albr.com.tax.repository.Product;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

import static org.junit.jupiter.api.Assertions.*;

class ProductMapperTest {

    private static ProductMapper mapper;

    @BeforeAll
    static void setUp() {
        mapper = Mappers.getMapper(ProductMapper.class);
        assertNotNull(mapper, "ProductMapper should be generated by MapStruct");
    }

    @Test
    void toEntity_returnsNull_whenInputNull() {
        assertNull(mapper.toEntity(null), "toEntity(null) must return null");
    }

    @Test
    void toResponse_returnsNull_whenInputNull() {
        assertNull(mapper.toResponse(null), "toResponse(null) must return null");
    }

    @Test
    void toEntity_smokeTest_withEmptyInstance() {
        // Ne fait aucune hypothèse sur les champs : simple instanciation
        ProductRequest req = new ProductRequest(); // suppose un ctor vide (classique)
        assertDoesNotThrow(() -> {
            var entity = mapper.toEntity(req);
            // MapStruct doit créer une instance de cible si possible
            assertNotNull(entity, "toEntity should not return null for a non-null input");
        });
    }

    @Test
    void toResponse_smokeTest_withEmptyInstance() {
        Product entity = new Product(); // suppose un ctor vide
        assertDoesNotThrow(() -> {
            ProductResponse resp = mapper.toResponse(entity);
            assertNotNull(resp, "toResponse should not return null for a non-null input");
        });
    }

    @Test
    void apiSurface_hasExpectedMethods() throws NoSuchMethodException {
        // Vérifie que les deux méthodes existent bien (signature)
        assertNotNull(ProductMapper.class.getMethod("toEntity", ProductRequest.class));
        assertNotNull(ProductMapper.class.getMethod("toResponse", Product.class));
    }
}


